### ISSUE TITLE
Request for information and authorization?

### ISSUE THREAD

**Issue by Lunastellia** [SubmergedAmongUs/Submerged#60]
Hello, I have many questions ;)

1 => I am using a custom interface inside my mod, I would like to know if I can use assets belonging to Submerged for a button to join the map (I just need the map logo)?

2 => Is it also possible to add content like hats/visors/nameplates created from Submerged assets?

3 => At the time of PolusGG there were cosmetics (hats), do you plan to make them available? Some were really cool and it would be cool if I could make them available for free to all players on my mod ^^

4 => Some of my roles require picking up items on the map, I read your license but using this function requires that I generate gameobjects on the map, is this still acceptable to you or not?

5 => Am I allowed to add settings... I want to add an option to disable O2 sabotage?

Greetings 
Lunastellia - AmongUs Challenger
orianagames.com

**Comment by AlexejheroYTB** [comment]
Hello, after discussing with the other developers and license holders, here are our answers.

1. ✅ The Submerged logo should be allowed to be used by anyone in any context without any license restrictions. The license will be amended to reflect this soon. In the meantime, you have our permission to use the logo.

2. ❕ You have our permission to use the Submerged assets to make cosmetics as long as you keep those cosmetics free within your mod and credit us for the original artwork.

3. ❌ The hats that were released on Polus.gg were Polus.gg hats and not Submerged hats, the two mods were never combined, they were just shared together. As such Submerged never had any hats. We also try to keep a minimal footprint with the mod so that it is compatible with other mods and as such we have no plans on adding hats or other cosmetics in the future.

4. ✅ That is fine, it is not against our license.

5. ✅ That is fine as well, it is not against our license either.

Please let me know if you have any further questions.

**Comment by Lunastellia** [comment]
Hi, thank you for your answers ;)

For polus.gg hats I will try to contact them ^^

Greetings
Lunastellia - AmongUs Challenger
orianagames.com
